[project]
name = "icai-muiaap-operacion-de-modelos-agusti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "carlosagustii", email = "carlosacanga03@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
]

[project.scripts]
icai-muiaap-operacion-de-modelos-agusti = "icai_muiaap_operacion_de_modelos_agusti:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
